---
title: "원자폭탄의 아버지들"
author: "오펜하이머"
date: "`r Sys.Date()`"
format: 
  pdf:
    documentclass: article
    geometry:                            # 4x6 배판 도서를 위한 설정
      # 이하 재단선이 없는 조판 ----------------------------------------------     
      # - paper=b5paper
      - paperheight=257mm
      - paperwidth=188mm
      - top=25mm    
      - headsep=10mm  
      - bottom=30mm     
      - footskip=15mm           
      - left=25mm
      - right=25mm
      - centering       
    latex_engine: xelatex
    keep_tex: false
    include-in-header:
      text: |    
        \usepackage{tikz}
        \usepackage{fontspec}
        \usepackage{tipa}
        \usepackage{setspace}
        \onehalfspacing

mainfont: "MaruBuri-Regular"
sansfont: "NanumSquareR"
monofont: "D2Codingligature"
editor_options: 
  chunk_output_type: console
---

# 소개

"오펜하이머"라는 이름[^1]은 독일 기원의 성씨로 가장 유명한 사람은 미국 물리학자 J. 로버트 오펜하이머이다. 그는 "원자폭탄의 아버지"로 알려져 있다.

[^1]: 오펜하이머는 영어로 \textipa{/ˈɑpənˌhaɪmər}} 로 발음된다.



# 표

아래는 간단한 표이다.

```{r}
#| echo: false
knitr::kable(
  matrix(c("행 1, 열 1", "행 1, 열 2", "행 2, 열 1", "행 2, 열 2"), ncol = 2),
  col.names = c("헤더 1", "헤더 2")
)
```


# 수식

다음은 간단한 수식이다:

$$
  f(x) = x^2
$$

# 다이어그램

아래는 간단한 다이어그램이다:

```{r, engine = 'tikz'}
#| echo: false
#| fig-align: "center"
\begin{tikzpicture}  % tikz로 그림을 그리기 시작
  \draw[->] (0,0) -- (4,0);  % x축 그리기
  \draw[->] (0,0) -- (0,4);  % y축 그리기
  \draw (0,0) -- (3,3);  % 대각선 그리기
\end{tikzpicture}
```

이 `.qmd` 파일은 Quarto를 사용하여 PDF로 렌더링할 수 있다. LaTeX 패키지와 명령어는 YAML 메타데이터의 `header-includes` 섹션에 추가될 수 있다. 그러나 특별한 LaTeX 명령어나 환경이 필요한 경우, 이를 수동으로 `.qmd` 파일에 적용해야 할 수도 있다.
