project:
  type: book
  # output-dir: docs # HTML
  output-dir: pdfs # PDF
  resources:
    - "data/*.mp3"
  render:
    - "*.qmd"
    - "!*.Rmd"
    - "!util.qmd"

lang: ko-KR
date-format: "YYYY년 MM월 DD일"

book:
  navbar:
    right:
      - icon: github
        href: https://github.com/bit2r/gpt-writing
        aria-label: GitHub
  google-analytics: "UA-229551680-1"
  title: "챗GPT 디지털 글쓰기"
  author: "이광춘, 신종화"
  date: last-modified
  chapters:
    - preface.qmd                    # OK
    - index.qmd                      # OK
    - whole_game.qmd                 # OK

    - part: "글쓰기 환경"
      chapters:
        - history.qmd                # OK
        - editor.qmd                 # OK
        - unicode.qmd                # OK
        - latex_pdf.qmd              # OK
        - quarto.qmd                 # OK

    - part: "글쓰기"
      chapters:
        - markdown_mess.qmd       # OK
        - writing.qmd                # OK

    - part: "기본요소"
      chapters:
        - components.qmd             # OK
        - markdown.qmd               # OK
        - document_class.qmd         # OK
        - about_book.qmd             # OK

    - part: "템플릿과 테마"
      chapters:
        - fonts.qmd                  # OK
        - colors.qmd                 # OK
        - themes_ggplot.qmd          # OK
        - themes_gt.qmd              # OK
        - templates.qmd              # OK

    - part: "출판물"
      chapters:
        - publishing.qmd          # OK
        - dw_book.qmd              # OK
        - dw_website.qmd          # OK
        - dw_slideshow.qmd        # OK
        - dw_dashboard.qmd        # OK

    - part: "챗GPT"
      chapters:
        - chatGPT.qmd             # OK
        - prompt.qmd              # OK
        - text_to_X.qmd           # OK
        - plugin.qmd              # OK

    - references.qmd

filters:
  - lightbox
  - parse-latex
  - line-highlight
lightbox: auto

format:
  html:
    theme:
      - cosmo
      - chatGPT4ds.scss
    number-depth: 3
    number-sections: true
    colorlinks: true
    code-overflow: wrap
    code-link: true
    author-meta: "이광춘"
    callout-appearance: simple
    editor_options:
      chunk_output_type: console

  pdf:
    documentclass: scrreprt
    cite-method: biblatex
    include-in-header:
      - text: |
          \usepackage{smartdiagram}
      - file: hangul_quarto.tex

bibliography: references.bib
csl: apa-single-spaced.csl
link-citations: true
tbl-cap-location: bottom

knitr:
  opts_chunk:
    message: false
    warning: false
    collapse: false
editor_options:
  chunk_output_type: console


execute:
  freeze: auto

editor: source

