project:
  type: book
  output-dir: docs
  resources:
    - "data/*.mp3"
  render:
    - "*.qmd"
    - "!*.Rmd"
    - "!util.qmd"

lang: ko-KR
date-format: "YYYY년 MM월 DD일"

book:
  title: "챗GPT 디지털 글쓰기"
  author: "이광춘"
  date: last-modified
  chapters:
    - preface.qmd
    - index.qmd
    - history.qmd

    - part: "글쓰기 환경"
      chapters:
        - editor.qmd
        - latex_pdf.qmd
        - quarto.qmd

    - part: "글쓰기"
      chapters:
        - markdown_01_mess.qmd
        - markdown_02_markdown.qmd
        - markdown_03_advanced.qmd
        - writing.qmd

    - part: "기본요소"
      chapters:
        - unicode.qmd
        - components.qmd
        - fonts.qmd
        - colors.qmd

    - part: "템플릿과 테마"
      chapters:
        - themes_ggplot.qmd
        - themes_gt.qmd
        - templates.qmd

    - part: "디지털 글쓰기"
      chapters:
        - whole_game.qmd
        - dw_pdf.qmd
        - dw_dashboard.qmd
        - dw_website.qmd  # 헬로월드만 제작
        - dw_slideshow.qmd
        - dw_blog.qmd

    - part: "실무"
      chapters:
        - publishing.qmd
        - about_book.qmd

    - references.qmd

filters:
  - lightbox
  - parse-latex
lightbox: auto

format:
  html:
    theme:
      - cosmo
      - chatGPT4ds.scss
    number-depth: 3
    number-sections: true
    colorlinks: true
    code-overflow: wrap
    code-link: true
    author-meta: "이광춘"
    callout-appearance: simple

  pdf:
    documentclass: scrreprt
    cite-method: biblatex
    include-in-header:
      - text: |
          \usepackage{smartdiagram}
      - file: hangul_quarto.tex

bibliography: references.bib
csl: apa-single-spaced.csl
link-citations: true
tbl-cap-location: bottom

knitr:
  opts_chunk:
    message: false
    warning: false
    collapse: false
editor_options:
  chunk_output_type: console


execute:
  freeze: auto

editor: source
