project:
  type: book
  output-dir: docs # HTML
  # output-dir: pdfs # PDF
  resources:
    - "data/*.mp3"
  render:
    - "*.qmd"
    - "!*.Rmd"
    - "!util.qmd"

lang: ko-KR
date-format: "YYYY년 MM월 DD일"

book:
  title: "챗GPT 디지털 글쓰기"
  author: "이광춘, 신종화"
  date: last-modified
  chapters:
    - preface.qmd   # OK
    - index.qmd     # OK
    - history.qmd   # OK

    - part: "글쓰기 환경"
      chapters:
        - editor.qmd        # OK
        - latex_pdf.qmd     # OK
        - quarto.qmd        # OK

    - part: "글쓰기"
      chapters:
        - markdown_01_mess.qmd       # OK
        - markdown_02_markdown.qmd   # OK
        - markdown_03_advanced.qmd   # OK
        - writing.qmd                # OK

    - part: "기본요소"
      chapters:
        - unicode.qmd                # OK
        - components.qmd             # OK
        - fonts.qmd                  # OK
        - colors.qmd                 # OK
        - document_class.qmd         # OK

    - part: "템플릿과 테마"
      chapters:
        - themes_ggplot.qmd          # OK
        - themes_gt.qmd              # OK
        - templates.qmd              # OK

    - part: "디지털 글쓰기"
      chapters:
        - whole_game.qmd          # OK
        - dw_pdf.qmd              # OK
        - dw_website.qmd          # OK
        - dw_slideshow.qmd        # OK
        - dw_blog.qmd             # OK
        - dw_dashboard.qmd        # OK

    - part: "실무"
      chapters:
        - publishing.qmd          # OK
        - about_book.qmd          # OK

    - references.qmd

filters:
  - lightbox
  - parse-latex
  - line-highlight
lightbox: auto

format:
  html:
    theme:
      - cosmo
      - chatGPT4ds.scss
    number-depth: 3
    number-sections: true
    colorlinks: true
    code-overflow: wrap
    code-link: true
    author-meta: "이광춘"
    callout-appearance: simple
    editor_options:
      chunk_output_type: console

  pdf:
    documentclass: scrreprt
    cite-method: biblatex
    include-in-header:
      - text: |
          \usepackage{smartdiagram}
      - file: hangul_quarto.tex

bibliography: references.bib
csl: apa-single-spaced.csl
link-citations: true
tbl-cap-location: bottom

knitr:
  opts_chunk:
    message: false
    warning: false
    collapse: false
editor_options:
  chunk_output_type: console


execute:
  freeze: auto

editor: source

